name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn -B test --file pom.xml
    - name: Upload Jacoco Site 
      uses: actions/upload-artifact@v4 # GitHub Action that allow to upload on the pipeline result a file or a directory
      with:
        name: jacoco-report
        path: ${{ github.workspace }}/target/site/jacoco
  deliver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
    - name: Upload JAR file
      uses: actions/upload-artifact@v4 # GitHub Action that allow to upload on the pipeline result a file or a directory
      with:
        name: jar-file
        path: ${{ github.workspace }}/target/book*.jar
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "murmuring-inlet-77824"
          heroku_email: "romainsessa@gmail.com"
